config/routes.rb
Rails.application.routes.draw do
  root "baits#index"

  resources :baits

  resources :tackle_box_items

  resources :fish_catches do
    resources :likes
  end

  get "activity", to: "activity#index"

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
end

app/models/fish_catch.rb
class FishCatch < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :bait
  belongs_to :user
  has_many :likes, dependent: :destroy

  after_create_commit -> {
    broadcast_prepend_later_to "activity", target: "catches", partial: "activity/fish_catch"
  }

  after_update_commit -> {
    broadcast_replace_later_to "activity",
    target: "#{dom_id(self)}_details",
    partial: "activity/catch_details"
  }

  after_destroy_commit -> {
    broadcast_remove_to "activity"
  }

  SPECIES = [
    "Brown Trout",
    "Rainbow Trout",
    "Lake Trout",
    "Largemouth Bass",
    "Smallmouth Bass",
    "Bluegill",
    "Walleye"
  ]

  validates :species, presence: true,
            inclusion: {
              in: SPECIES,
              message: "%{value} is not a valid species"
            }

  validates :weight, :length,
            presence: true,
            numericality: { greater_than: 0 }

  attr_accessor :my_like

  scope :with_species, ->(species) {
    where(species: species) if species.present?
  }

  scope :with_bait_name, ->(bait_name) {
    where(baits: {name: bait_name}) if bait_name.present?
  }

  scope :with_weight_between, ->(low, high) {
    where(weight: low..high) if low.present? && high.present?
  }
end

app/controllers/fish_catches_controller.rb
class FishCatchesController < ApplicationController
  before_action :require_signin
  before_action :set_fish_catch, only: %i[show edit update destroy]

  def index
    @pagy, @fish_catches =
      pagy(current_user.filter_catches(params),
          items: params[:per_page] ||= 5,
          link_extra: 'data-turbo-action="advance"'
          )

    @bait_names = Bait.pluck(:name)
    @species = FishCatch::SPECIES

    @min_weight = current_user.min_catch_weight
    @max_weight = current_user.max_catch_weight
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @fish_catch.update(fish_catch_params)
        flash.now[:notice] = "Catch successfully updated."

        format.turbo_stream do
          @fish_catches = fish_catches_for_bait(@fish_catch.bait)
        end

        format.html { redirect_to tackle_box_item_for_catch(@fish_catch) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def create
    @fish_catch = current_user.fish_catches.new(fish_catch_params)

    respond_to do |format|
      if @fish_catch.save
        flash.now[:notice] = "Catch successfully created."

        format.turbo_stream do
          @fish_catches = fish_catches_for_bait(@fish_catch.bait)
          @new_catch = current_user.fish_catches.new(bait: @fish_catch.bait)
        end

        format.html { redirect_to tackle_box_item_for_catch(@fish_catch) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fish_catch.destroy

    flash.now[:notice] = "Catch successfully deleted."

    respond_to do |format|
      format.turbo_stream do
        @fish_catches = fish_catches_for_bait(@fish_catch.bait)
      end

      format.html { redirect_to tackle_box_item_for_catch(@fish_catch) }
    end
  end

private

  def set_fish_catch
    @fish_catch = current_user.fish_catches.find(params[:id])
  end

  def fish_catch_params
    params.require(:fish_catch).permit(:species, :weight, :length, :bait_id)
  end

  def tackle_box_item_for_catch(fish_catch)
    current_user.tackle_box_items.find_sole_by(bait: fish_catch.bait)
  end

  def fish_catches_for_bait(bait)
    current_user.fish_catches.where(bait: bait).select(:weight)
  end
end

app/helpers/fish_catches_helper.rb
module FishCatchesHelper

  def total_weight(fish_catches)
    fish_catches.map(&:weight).reduce(0, &:+)
  end

  def sort_link_to(name, column)
    name = raw("#{name} #{direction_indicator(column)}")

    params = request.params.
      merge(sort: column, direction: next_direction(column))

    link_to name, params, data: { turbo_action: "advance", action: "turbo:click->sort-link#updateForm" }
  end

  def next_direction(column)
    if currently_sorted?(column)
      params[:direction] == "asc" ? "desc" : "asc"
    else
      "asc"
    end
  end

  def direction_indicator(column)
    if currently_sorted?(column)
      tag.span(class: "sort sort-#{next_direction(column)}")
    end
  end

  def currently_sorted?(column)
    params[:sort] == column.to_s
  end

  def render_update_stats_stream(fish_catches)
    turbo_stream.update "stats" do
      render "tackle_box_items/stats", fish_catches: fish_catches
    end
  end

end

app/views/fish_catches/_fish_catch.html.erb
<%= turbo_frame_tag fish_catch do %>
  <div class="catch">
    <div class="species">
      <%= fish_catch.species %>
    </div>
    <div class="weight">
      <%= fish_catch.weight %> lbs
    </div>
    <div class="length">
      <%= fish_catch.length %> in
    </div>
    <div class="actions">
      <%= link_to image_tag("pencil.svg"),
                  edit_fish_catch_path(fish_catch)%>

      <%= button_to fish_catch_path(fish_catch), method: :delete,
          form: { data: { turbo_confirm: "Are you sure?" } } do %>
        <%= image_tag("trash.svg") %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/fish_catches/_form.html.erb
<%= form_with(model: fish_catch) do |f| %>
  <div>
    <%= f.label :species %>
    <%= f.select :species, FishCatch::SPECIES,
                   {include_blank: "Species" },
                   {required: true, autofocus: true} %>
  </div>

  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight, step: "any",
                       placeholder: "Weight (lbs)",
                       required: true %>
  </div>

  <div>
    <%= f.label :length %>
    <%= f.number_field :length, step: "any",
                       placeholder: "Length (in)",
                       required: true %>
  </div>

  <%= f.hidden_field :bait_id, value: fish_catch.bait_id %>

  <% if fish_catch.new_record? %>
    <%= f.submit "Log Catch" %>
  <% else %>
    <div class="save-cancel">
      <%= f.submit "Save" %>
      <%= link_to "Cancel", @fish_catch %>
    </div>
  <% end %>
<% end %>

app/views/fish_catches/_no_catches.html.erb
<div class="no-catches">
  <h2>
    Sorry, no catches yet. 😕
  </h2>
  <p>
    <%= link_to "Log a catch!", tackle_box_items_path, data: { turbo_frame: "_top" } %>
  </p>
</div>

app/views/fish_catches/create.turbo_stream.erb
<%= render_update_stats_stream(@fish_catches) %>

<%= turbo_stream.prepend "catches", @fish_catch %>

<%= turbo_stream.update "new_catch",
  partial: "form",
  locals: { fish_catch: @new_catch }
%>

<%= render_flash_stream %>

app/views/fish_catches/destroy.turbo_stream.erb
<%= render_update_stats_stream(@fish_catches) %>

<%= turbo_stream.remove @fish_catch %>

<%= render_flash_stream %>

app/views/fish_catches/edit.html.erb
<h2>Edit Fish Catch</h2>

<%= turbo_frame_tag @fish_catch do %>
  <div class="edit">
    <%= render "form", fish_catch: @fish_catch %>
  </div>
<% end %>

app/views/fish_catches/index.html.erb
<div data-controller="sort-link">
  <div class="filter">
    <%= form_with(url: fish_catches_path, method: :get,
        data: {
          turbo_frame: "catches",
          turbo_action: "advance",
          controller: "form",
          action: "input->form#submit"
      }) do |f| %>
      <div class="row-1">
        <div>
          <%= f.select :bait, @bait_names,
              include_blank: "Any Bait", selected: params[:bait] %>
        </div>
        <div>
          <%= f.select :species, @species,
              include_blank: "Any Species", selected: params[:species] %>
        </div>

        <%= f.hidden_field :sort, value: params[:sort], data: { sort_link_target: "sort" } %>
        <%= f.hidden_field :direction, value: params[:direction], data: { sort_link_target: "direction" } %>

        <div
          class="weight"
          data-controller="range-slider"
          data-range-slider-min-value="<%= @min_weight%>"
          data-range-slider-max-value="<%= @max_weight%>"
        >
          <div data-range-slider-target="slider">

          </div>

          <div class="flex">
            <%= f.hidden_field :min_weight,
                value: params[:min_weight] || @min_weight,
                data: { range_slider_target: "currentMin" }
            %>
            <%= f.hidden_field :max_weight,
                value: params[:max_weight] || @max_weight,
                data: { range_slider_target: "currentMax" }
            %>
          </div>

          <div class="label">
            Weight
          </div>
        </div>
      </div>

      <div class="row-2">
        Show
        <%= f.select :per_page,
              options_for_select([5, 10, 25, 50, 100],
              selected: params[:per_page]) %>
      </div>
    <% end %>
  </div>

  <%= turbo_frame_tag "catches" do %>
    <% if @fish_catches.any? %>
      <div class="fish-catches">
        <table>
          <thead>
            <tr>
              <th class="bait">
                <%= sort_link_to "Bait", "bait" %>
              </th>
              <th class="species">
                <%= sort_link_to "Species", "species" %>
              </th>
              <th class="weight">
                <%= sort_link_to "Weight", "weight" %>
              </th>
              <th class="length">
                <%= sort_link_to "Length", "length" %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @fish_catches.each do |fish_catch| %>
              <tr>
                <td class="bait">
                  <%= fish_catch.bait.name %>
                </td>
                <td class="species">
                  <%= fish_catch.species %>
                </td>
                <td class="weight">
                  <%= fish_catch.weight %> lbs
                </td>
                <td class="length">
                  <%= fish_catch.length %> in
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% if @pagy.pages > 1 %>
          <div class="footer">
            <%== pagy_nav(@pagy) %>
          </div>
        <% end %>
      </div>
    <% else %>
      <%= render "no_catches" %>
    <% end %>
  <% end %>
</div>

app/views/fish_catches/new.html.erb
<h2>New Fish Catch</h2>

<%= turbo_frame_tag "new_catch" do %>
  <%= render "form", fish_catch: @fish_catch %>
<% end %>

app/views/fish_catches/show.html.erb
<%= render @fish_catch %>

app/views/fish_catches/update.turbo_stream.erb
<%= render_update_stats_stream(@fish_catches) %>

<%= turbo_stream.replace @fish_catch, @fish_catch %>

<%= render_flash_stream %>