config/routes.rb
Rails.application.routes.draw do
  root "baits#index"

  resources :baits

  resources :tackle_box_items

  resources :fish_catches do
    resources :likes
  end

  get "activity", to: "activity#index"

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  before_action :require_signin

  def index
    @pagy, @fish_catches = pagy(
      FishCatch.order(created_at: :desc).includes(:user, :bait),
      items: 5
    )

    @fish_catches = current_user.assign_my_likes_to_catches(@fish_catches)
  end
end

app/views/activity/_catch_details.html.erb
<%= tag.div class: "details", id: "#{dom_id(fish_catch)}_details" do %>
  <div>
    <%= link_to image_tag(fish_catch.bait.image), fish_catch.bait %>
  </div>
  <div>
    <span class="user">
      <%= fish_catch.user.username %>
    </span>
    caught a
    <span class="species">
      <%= fish_catch.species %>
    </span>
    weighing
    <span class="weight">
      <%= fish_catch.weight %> lbs
    </span>
    and measuring
    <span class="length">
      <%= fish_catch.length %> in
    </span>
  </div>
<% end %>

app/views/activity/_catch_likes.html.erb
<%= turbo_frame_tag "#{dom_id(fish_catch)}_likes" do %>
  <% if like = fish_catch.my_like %>
    <%= button_to fish_catch_like_path(fish_catch, like), method: :delete do %>
      <%= image_tag("full-heart.svg") %>
      <%= tag.div id: "#{dom_id(fish_catch)}_likes_count" do %>
        <%= fish_catch.likes_count %>
      <% end %>
    <% end %>
  <% else %>
    <%= button_to fish_catch_likes_path(fish_catch) do %>
      <%= image_tag("empty-heart.svg") %>
      <%= tag.div id: "#{dom_id(fish_catch)}_likes_count" do %>
        <%= fish_catch.likes_count %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/activity/_fish_catch.html.erb
<%= tag.div class: "catch", id: dom_id(fish_catch) do %>
  <%= render "activity/catch_details", fish_catch: fish_catch %>

  <%= render "activity/catch_likes", fish_catch: fish_catch %>
<% end%>

app/views/activity/index.html.erb
<%= turbo_stream_from "activity" %>

<div id="catches">
  <%= turbo_frame_tag "catches_page_#{@pagy.page}" do %>
    <%= render collection: @fish_catches,
        partial: "activity/fish_catch" %>

    <% if @pagy.next %>
      <%= turbo_frame_tag "catches_page_#{@pagy.next}",
          src: activity_path(page: @pagy.next),
          loading: :lazy do
      %>
      <div class="loader"></div>
      <% end %>
    <% end %>
  <% end %>
</div>