config/routes.rb
Rails.application.routes.draw do
  root "baits#index"

  resources :baits

  resources :tackle_box_items

  resources :fish_catches do
    resources :likes
  end

  get "activity", to: "activity#index"

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
end

app/models/bait.rb
class Bait < ApplicationRecord
  has_many :fish_catches

  validates :name, presence: true, uniqueness: true
  validates :category, :image, presence: true

  attr_accessor :my_tackle_box_item

  scope :with_name, ->(name) {
    where("lower(name) LIKE ?", "%#{name.downcase}%") if name.present?
  }

  scope :with_category, ->(category) {
    where(category: category) if category.present?
  }

  def self.search(params={})
    sort_column =
      params[:sort]
        .presence_in(%w{ name tackle_box_items_count }) || "id"

    sort_direction =
      sort_column == "tackle_box_items_count" ? :desc : :asc

    self
      .with_name(params[:name])
      .with_category(params[:category])
      .order(sort_column => sort_direction)
  end
end

app/controllers/baits_controller.rb
class BaitsController < ApplicationController

  def index
    @baits = Bait.search(params)

    @bait_categories = Bait.pluck(:category).uniq

    if signed_in?
      @baits = current_user.assign_my_tackle_box_items_to_baits(@baits)
    end
  end

  def show
    @bait = Bait.find(params[:id])

    @top_catches =
      @bait.fish_catches.order(weight: :desc).limit(10).includes(:user)
  end

end

app/views/baits/_bait.html.erb
<%= tag.div id: dom_id(bait) do %>
  <div class="bait">
    <%= current_second %>
    <%= link_to image_tag(bait.image), bait, data: { turbo_frame: "_top" } %>
    <div class="name">
      <%= link_to bait.name, bait, data: { turbo_frame: "_top" } %>
    </div>
    <div class="category">
      <%= bait.category %>
    </div>
    <div class="popularity">
      <%= bait.tackle_box_items_count %>
    </div>
    <% if signed_in? %>
      <% if item = bait.my_tackle_box_item %>
        <%= button_to "Remove", tackle_box_item_path(item),
                      method: :delete %>
      <% else %>
        <%= button_to "Add", tackle_box_items_path(bait_id: bait) %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/baits/index.html.erb
<div class="search">
  <%= form_with(
      url: baits_path,
      method: :get,
      data: { turbo_frame: "baits_results", controller: "form", action: "input->form#submit" }
    ) do |f| %>
    <div>
      <%= f.search_field :name, placeholder: 'Name...',
            value: params[:name] %>
    </div>
    <div>
      <%= f.select :category, @bait_categories,
            include_blank: "Any Category", selected: params[:category] %>
    </div>
    <div>
      <%= f.select :sort,
            [["By Name", "name"], ["By Popularity", "tackle_box_items_count"]],
            include_blank: "Sort By", selected: params[:sort] %>
    </div>
  <% end %>
</div>

<%= turbo_frame_tag "baits_results", data: { turbo_action: "advance" } do %>
  <div class="baits">
    <%= render @baits %>
  </div>
<% end %>

app/views/baits/show.html.erb
<div class="header">
  <div>
    <h2 class="name">
      <%= @bait.name %>
    </h2>
    <div class="category">
      <%= @bait.category %>
    </div>
    <div class="description">
      <%= @bait.description %>
    </div>
  </div>
  <%= image_tag @bait.image %>
</div>

<h3>Top 10 Catches</h3>
<table class="top-catches">
  <tbody>
    <% @top_catches.each do |fish_catch| %>
      <tr>
        <td class="weight">
          <%= fish_catch.weight %> lbs
        </td>
        <td class="species">
          <%= fish_catch.species %>
        </td>
        <td class="user">
          <%= fish_catch.user.username %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>