config/routes.rb
Rails.application.routes.draw do
  root "baits#index"

  resources :baits

  resources :tackle_box_items

  resources :fish_catches do
    resources :likes
  end

  get "activity", to: "activity#index"

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
end

app/views/layouts/_flash.html.erb
<div class="flashes" id="flash">
  <% flash.each do |type, message| %>
    <%= content_tag(:div, message, class: "flash #{type}",
      data: { controller: "flash" })
    %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    No 🐟 🐠 🐡 were harmed in the making of this app.
  </p>
  <p>
    Learn to 🎣 with
    <a href="https://pragmaticstudio.com">The Pragmatic Studio</a>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="primary">
    <ul>
      <% if signed_in? %>
        <li>
          <%= nav_link_to current_user.username, current_user %>
        </li>
        <li>
          <%= button_to "Sign Out", session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= nav_link_to "Sign In", signin_path %>
        </li>
        <li>
          <%= nav_link_to "Sign Up", signup_path %>
        </li>
      <% end %>
    </ul>
  </nav>

  <div class="logo">
    <%= link_to baits_path do %>
      <%= image_tag("logo.svg") %>
      <h1>Gone Fishin'</h1>
    <% end %>
  </div>

  <nav class="secondary">
    <ul>
      <li>
        <%= nav_link_to "Baits", baits_path %>
      </li>
      <li>
        <%= nav_link_to "Tackle Box", tackle_box_items_path %>
        <% if signed_in? %>
          <div class="item-count" id="tackle_box_items_count" data-turbo-permanent>
            <%= current_user.tackle_box_items.size %>
          </div>
        <% end %>
      </li>
      <li>
        <%= nav_link_to "Catches", fish_catches_path %>
      </li>
      <li>
        <%= nav_link_to "Activity", activity_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gone Fishin'</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <%= render "layouts/flash" %>

    <main>
      <div id="<%= content_id %>">
        <%= yield %>
      </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>